### ISSUE TITLE
Automation list not populated in ardour 6

### ISSUE THREAD

**Issue by cancandan** [drlight-code/osccontrol-light#41]
I was able to load the plugin in ardour 6 but can not see the controls specified in .yaml. They dont show up in the automation options in ardour. That is, when you press the A button on a track, then select processor automation and then osccontrol-light, the only thing that shows up is "Plugin Enable"

**Comment by cancandan** [comment]
It works in ardour 6, I had to clear the "blacklist". However multiple instances do not work as stated in
[https://github.com/drlight-code/osccontrol-light/issues/35](https://github.com/drlight-code/osccontrol-light/issues/35)

**Comment by drlight-code** [comment]
Hi, glad you could figure it out! The problem with multiple instances is related to how some hosts (including Ardour) identify the plugins. There is a unique "plugin key" that can be set by an unmodified JUCE only during compile time for VST2 plugins. Some hosts uniquely identify a plugin based on that, so you will only see one instance in the list of available plugins. Bitwig Studio for example seems to use the filesystem node to uniquely identify plugins, so there it works without problems. Since I would not like to ship a modified JUCE version I did not look into this further for the time being, as I was waiting for JUCE 6 to come out.

As it so happens the JUCE 6 preview release was just announced 30 minutes ago. With JUCE 6 VST3 will be supported on Linux, on which I am developing. I hope that with VST3 the plugin identifier is no longer hardcoded in that fashion and that I can find the time soon to look into this again. For the time being you'll have to live with a single plugin instance, in Ardour at least, and I hope that the plugin is somewhat useful to you nonetheless.
